version: '3.4'

services:
  studentapi:
    image: ${DOCKER_REGISTRY-}studentapi
    build:
      context: .
      dockerfile: StudentAPI/Dockerfile
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"